name = "fs"
handle_accessor = "crate::ipc::fs::get_handle_for_fs"
struct_name = "FSServerStruct"
lifetimes = "<'a>"

[main_interface]
session_name = "FSSession"
lifetimes = "<'a>"

[[main_interface.methods]]
name = "open_file"
id = 1
inputs = [{ name = "filename", ty = "String"}]
output = "OSResult<TranslateMoveHandle>"

[[sub_interfaces]]
session_name = "IFileSession"
lifetimes = "<'a>"

[[sub_interfaces.methods]]
name = "read_file"
id = 1
inputs = [{ name = "length", ty = "usize" }]
output = "OSResult<usize>"
