name = "fs"
struct_name = "FSServerStruct"
handle_accessor = "crate::ipc::fs::get_handle_for_fs"

[[methods]]
name = "open_file"
id = 1
inputs = [{ name = "filename", ty = "String"}]
output = "OSResult<u32>"
