name = "fs"
handle_accessor = "crate::ipc::fs::get_handle_for_fs"

[main_interface]
struct_name = "FSServerStruct"
session_name = "FSSession"

[[main_interface.methods]]
name = "open_file"
id = 1
inputs = [{ name = "filename", ty = "String"}]
output = "OSResult<TranslateMoveHandle>"