name = "sm"
struct_name = "SMServerStruct"
handle_accessor = "crate::ipc::sm::get_handle_for_sm"

[[methods]]
name = "get_service_handle"
id = 1
inputs = [{ name = "tag", ty = "u64"}]
output = "OSResult<TranslateMoveHandle>"
is_async = true

[[methods]]
name = "register_port"
id = 2
inputs = [{ name = "tag", ty = "u64"}, { name = "port_handle", ty = "TranslateCopyHandle"} ]
output = "OSResult<()>"
is_async = true