[workspace]
members = [
  "francium",
  "francium/pc_bootloader",
  "libprocess",
  "libcommon",
  "modules/fs",
  "modules/sm",
  "modules/test",
  "ipc-gen"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
overflow-checks = true
