[package]
name = "francium_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"bitflags" = "1.2.1"
num-traits = { version = "0.2", default-features = false }
num-derive = "0.2"