[package]
name = "francium"
version = "0.1.0"
authors = ["Ezekiel Bethel <zek@9net.org>"]
edition = "2018"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"bitflags" = "1.2.1"
elf_rs = "0.1.3"
lazy_static = { version = "1.4.0", features=["spin_no_std"]}
smallvec = "1.6.1"
spin = "0.9.0"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
overflow-checks = true

[features]
platform_virt = []
platform_raspi4 = []

[[bin]]
name = "francium_virt"
required-features = ["platform_virt"]
path = "src/main.rs"

[[bin]]
name = "francium_raspi4"
required-features = ["platform_raspi4"]
path = "src/main.rs"