[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "aarch64-unknown-francium.json"

[target.aarch64-unknown-francium]
rustflags = ["-C", "link-arg=-Tlink.x"]