[package]
name = "francium_pc_bootimg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.11"
francium_pc = { path = "../francium_pc", artifact = "bin", target = "x86_64-unknown-none" }